routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Video\Http\Controllers\VideoController;
use Video\Http\Controllers\CategoryController;


Route::middleware('web')->group(function (){

    Route::group(['prefix'=>"admin", 'as'=>'admin.', 'middleware' => 'is_admin'],static function(){
        Route::resource('video', VideoController::class);
        Route::resource('video_category', CategoryController::class);
        Route::get('settings/video', [VideoController::class,'settings'])->name('video.settings');
        Route::get('category/video/publish/{video_category}', [CategoryController::class,'publish'])->name('video_category.publish');
        Route::post('category/video/order', [CategoryController::class,'order'])->name('video_category.order');
        Route::post('settings/video/{settings}', [VideoController::class,'settingsUpdate'])->name('video.settings.update');
    });
    try {
         $settings = \Video\Models\Settings::find(1);
         Route::get('/'.$settings->url,[VideoController::class,'frontIndex'])->name('video');
         Route::get('/'.$settings->url . '/{url}',[CategoryController::class,'show'])->name('video.category');
    } catch (Exception $exception) {
        //throw $th;
    }
});

resources/views/category/index.blade.php
@extends('layouts.admin')
@section('title',"Видео")
@section('content')
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <x-admin.navigation :links="$links" />
                <div class="card-body">
                    <x-warning />
                    <div class="row row-page-create">
                        <div class="col-md-8 order-md-first">
                            <div class="dd nestable" id="nestable" data-max="1">
                                <x-video::admin.category.categories :categories="$categories"/>
                            </div>
                        </div>
                        <div class="col-md-4 order-md-first ">
                            <x-video::admin.category.form />
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <input type="hidden" id="route_dd" value="{{  route('admin.video_category.order') }}">
    <script src="{{asset('assets/js/admin/dnd.js')}}" ></script>
    @vite('resources/js/video/category/edit.js')
    <script src="{{ asset('assets/js/admin/delete.js') }}"></script>
    <script src="{{ asset('assets/js/admin/show.js') }}"></script>
@endsection
@section("breadcrumb")
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.video.index")}}">Видео</a></li>
            <li class="breadcrumb-item active" aria-current="page">Категории</li>
        </ol>
    </div>
@endsection

resources/views/video/category.blade.php
@extends('layouts.admin')
@section('title',"Статьи")
@section('content')
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <x-admin.navigation :links="$links" />
                <x-articles::category />
            </div>
        </div>
    </div>
@endsection

resources/views/video/create.blade.php
@extends('layouts.admin')
@section('title',"Статьи")
@section('content')
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <x-admin.navigation :links="$links" />
                <x-articles::create :links="$linksContent" />
            </div>
        </div>
    </div>
@endsection

resources/views/video/edit.blade.php
@extends('layouts.admin')
@section('title',"Статьи")
@section('content')
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <x-admin.navigation :links="$links" />
                <x-articles::edit :links="$linksContent" :article="$article" />
            </div>
        </div>
    </div>
@endsection
@section("breadcrumb")
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.video.index")}}">Видео</a></li>
            <li class="breadcrumb-item active" aria-current="page">Редактировать</li>
        </ol>
    </div>
@endsection

resources/views/video/front/articles.blade.php
{{-- @dd($news) --}}
@extends('layouts.inner')
@section('title',$article->seoTitle)
@section('description',$article->seoDescription)
@section('keywords',$article->seoKeywords)
@section('page',true)
@section('content')
<div class="content">

    <x-articles::front.item :article="$article" />
</div>

@endsection

resources/views/video/front/index.blade.php
@extends('layouts.inner')
@section('title',$settings->seoTitle ?? $settings->title)
@section('description',$settings->seoDescription)
@section('keywords',$settings->seoKeywords)
@section('page',true)
@section('content')
<div class="content">
    {{-- <x-front.breadcrumbs :breadcrumbs="$breadcrumbs" /> --}}
    {{-- <h2>{{ $title }}</h2> --}}
    @dd($videos)
</div>

@endsection

resources/views/video/front/show.blade.php
@extends('layouts.inner')
@section('title',$settings->title)
@section('description',$settings->description)
@section('keywords',$settings->keywords)
@section('page',true)
@section('content')
    <div class="content">
        {{-- <x-front.breadcrumbs :breadcrumbs="$breadcrumbs" /> --}}
        {{-- <h2>{{ $title }}</h2> --}}
        @dd($videos)
    </div>

@endsection

resources/views/video/index.blade.php
@extends('layouts.admin')
@section('title',"Видео")
@section('content')
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <x-admin.navigation :links="$links" />
                <div class="card-body">
                    <x-warning />
                    <div class="row">
                        <ul class="list-group col-lg-8">
                            <x-video::admin.video />
                        </ul>
                        <div class="col-lg-4">
                            <x-video::admin.video_form />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    @vite('resources/js/video/edit.js')
    <script src="{{ asset('assets/js/admin/delete.js') }}"></script>
@endsection
@section("breadcrumb")
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page">Видео</li>
        </ol>
    </div>
@endsection

resources/views/video/settings.blade.php
@extends('layouts.admin')
@section('title',"Видео")
@section('content')
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <x-admin.navigation :links="$links" />
                <x-video::settings />
            </div>
        </div>
    </div>
@endsection
@section("breadcrumb")
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.video.index")}}">Видео</a></li>
            <li class="breadcrumb-item active" aria-current="page">Настройки</li>
        </ol>
    </div>
@endsection